### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by knowMe228** [magicred7/ngrocker#1]
![изображение](https://user-images.githubusercontent.com/45036031/152645620-5fc5cfa9-5750-4266-8b40-a375730d35b6.png)
what needs to be done to make it work properly?

**Comment by ECRomaneli** [comment]
Hey @knowMe228!
This project is already deprecated and no longer been supported. To reach the same objetive you may like to try projects like the https://github.com/ofabricio/capture. I am also working to create an Open-Source solution to provide tunneling, reverse-proxy and sniffer at the same application.
